# Introduction

Particulate organic carbon (POC) is one of the most important pools of organic carbon found in the ocean.
It takes part in various biological process and influences both organic and inorganic carbon cycles (Liu et al., 2019b) and composed of living materials (Phytoplankton, zooplankton, bacteria, etc.) and detritus.
Particulate organic carbon is an important pathway by which organic carbon (formed via photosynthesis) is transferred from the surface to deeper ocean layers where it may be sequestered.
It is often used as an indicator of productivity in the euphotic zone (Fingas, 2018).
Some zooplankton, such as appendicularians and pteropods, discard gelatinous materials in the surface waters as part of their normal activities.
These materials can account for extremely high local POC values in the surface waters (Wangersky, 1977).
Although particulate organic carbon (POC) is only 1--10% of dissolved organic carbon (Parsons 1975) in the seawater, the study on POC has become a hot topic of marine sciences because of its importance in marine food chain and marine productivity (Shen, Zhiliang; Yang, Heming & Liu, 2020).

One of the main sources of POC input to estuaries is by their associated rivers (Bianchi and Bauer, 2012).
On a global scale, rivers deliver approximately 2.0×108 t C/yr.
of POC into marginal seas (Liu et al., 2019a).
The photosynthetic fixation of inorganic carbon and nutrients into plant biomass is the ultimate source of POC in estuarine and coastal systems.
The consumption and transformation of organic matter through metazoan and microbial (e.g., microbial loop) trophic levels are critical in the cycling of POC in estuaries and coastal systems (Bianchi et al., 2007; Wetzel, 1995).

POC concentration in ocean is affected by phytoplankton (Fernandes et al., 2009) in association with physical parameters like; light, nutrients, chlorophyll-a concentration, salinity, temperature (Stramska, 2014).
Except this, terrigenous POC transported by river discharge (Wang et al., 2012).
riverbed erosion (Xu and Milliman, 2009), current (Fan et al., 2018), wind speed and tidal flow (Liu et al., 2019b), SST (Fernandes et al., 2009) also responsible for POC contribution in ocean.
Seasonal and annual variations in hydrology, including storm and hurricane events, further influence the input, dispersion, and cycling of POC.
Several studies have indicated that remineralization and remobilization also play important roles in controlling POC variation on the shelf (Le et al., 2017).

The global ocean surface wind vector (wind speed and direction) field provides essential environmental information.
It is critical data for short-term weather forecasts and warnings, nowcasting, climatology, and oceanography studies (Gaiser et al., 2004).
Wind can enhance sediment resuspension and vertical mixing (He et al., 2013).
So, wind vector is an important factor for the variability of POC concentration in the ocean.

POC is composed of suspended particles whose light absorption and back scattering features can be recorded by satellite sensors.
(Liu et al., 2019b).
The use of satellite-based sensors to estimate POC in the estuary, lakes and global ocean provides numerous advantages with respect to standard field measurement (Le et al., 2017; Liu et al., 2015; Stramski et al., 1999a).
The efficiency of satellite measurement depends on the optical characteristics of the water body.
There are several satellite systems in operation today that collect imagery that is subsequently distribute POC data to users such as MODIS Aqua (Moderate Resolution Imaging Spectroradiometer), Oceansat-2 (OCM-2: Ocean Color Monitor-2) and other satellites which have Chl-a absorption bands like Sentinal-3 (OLCI- Ocean and Land Color Instrument), Landsat 8.
Among these, MODIS (or Moderate Resolution Imaging Spectroradiometer) Aqua data is frequently used to estimate the distribution of POC in different parts of world ocean (Duan et al., 2014).

Recently, spatial and temporal variability of POC have been studied in Yellow Bohai sea Surface POC is highest in spring (452 ± 53.6 mgm-3) in the Yellow Bohai Sea in China, and lowest in summer (245 ± 84.8 mgm-3) in this sea (Fan et al., 2018).
The spatial and seasonal patterns of POC are due to combined influences of primary productivity, water exchange, sediment resuspension and terrestrial inputs.
Le et al., (2019) studied POC of two riverbed estuaries in the north Gulf of Mexico.
They found that POC concentration may change with changing of season.
POC in winter and spring was higher than summer and fall.
It also changes with year basis.
The highest measured POC occurred in March 2003, with a mean value of 506.1±442.2 mgm-3 and a median value of 353.0 mgm-3.
The lowest POC occurred in November 2003, with a mean value of 310.6±324.0 mgm-3.
Liu et al., (2015) studied POC distribution in pearl river estuary, China.
They found that in situ POC concentrations were ranged between 0.4 mgm-3 and 0.6 mgm-3.
The monthly decrease trend of POC concentration was mainly driven by its significant decrease in wet season (May to October) due to low flow velocity, sediment resuspension (Liu et al., 2019a).

Many researches work have been done for understanding the variability of POC distribution in different ocean such as Pacific (Fan et al., 2018; Pavia et al., 2019), Atlantic (Stramska, 2014), Southern ocean (Zhu et al., 2011) and global scale (Gardner et al., 2006; Stramska, 2009; Świrgoń and Stramska, 2015).
However, little information is available on the distribution of POC in the Indian Ocean (Bhosle et al., 1988) in general, and in the Bay of Bengal (Fernandes et al., 2009; Nandakumar et al., 1987) in particular where the large-scale and long time series data and analysis are insufficient.
Remarkably, no study has been conducted yet emphasizing the seasonal variability of POC in the Bangladesh part of BoB.
In addition, there is a lack of research on the relationship between changes in POC and other parameters (physical and environmental) in this sea.

Satellite data indicate a decrease in the global primary productivity meaning that there is a negative trend in POC in global ocean.
The decrease of POC concertation per year could indicate that the biological carbon cycle in the ocean is weakening (Xie et al., 2019).
Hence, a baseline study is required to know the level and distribution of POC and associated influencing factors and their level of contribution on the variability which would give us the health status of the marine ecosystems by providing a means for advancing a methodology to diagnose rates and fluxes of relevance to the global carbon cycle and to constrain the uncertainties of carbon budgets.
This gap is the motivation of this research to understand more about the seasonal distribution of POC in the BoB and the relationship between POC and other parameters.
In the present research, we considered 18 years (2002-2019) POC data value for estimating seasonal variability of POC in the BoB following the data collected from MODIS Aqua satellite.

## Objectives of the study

- To identify the seasonal trends of POC distribution.
- Find out season-wise relationship between POC and SST in the BoB.
- Find out season-wise relationship between POC and Chl-a in the BoB.
- Find out season-wise relationship between POC and wind vector.
- To validate the MODIS Aqua satellite-based POC with and in-situ measurements.
