# Discussion

## Seasonal trend of POC 
The surface concentrations of POC varied from 103.08 to 184.22 mgm-3 in the northern BoB (Fig. 4.1). Fernandes et al. (2009)  also observed the concentration of POC from 51.6 to 133.2 mgm-3 in the BoB. The observed seasonal differences in POC appears to be governed by river run-off and physical forces such as eddies which pump nutrients into the surface waters thereby enhancing biological production (Fernandes et al., 2009). The seasonal variability of POC was significant in the northern BoB in this study. Fernandes et al., (2009) also observed the significant difference of POC variability among the seasons in both offshore and near stations of the BoB due to nutrient addition by organic matter production.  Similar result was found by Allison et al., (2010) in the southern ocean.

### Southwest monsoon (June – September)
Among the seasons, reasonably low POC was observed in this season (141.31 ±36.40 mgm-³). Highest SST was recorded (30.58 0C) at the beginning of this seasons and responsible for this lower POC. Insufficient freshwater influx can also be a major cause for the lower range of POC (Nagamani et al., 2011). As surface water warms because of high SST, the stratification being pronounced, mixing is suppressed, and transfer of nutrients is decreased from deeper to surface waters. Therefore, phytoplankton productivity declines and  POC becomes low (Stramska and Bialogrodzka, 2016). In southwest monsoon, prevailing southwesterly winds  may have contributed to low POC in the inner, middle and outer shelves. Similar observation was also reported by  Liu et al., (2015). 

### Post Monsoon (October- November) 
Beginning of post monsoon POC starts to rise (Fig. 4.1). Relatively high POC (162.33±28.16 mgm-³) was observed in this season than the southwest monsoon because  the wind forces the nutrient rich water to reach the surface for phytoplankton cells to grow (Sarangi and Devi, 2017). Gomes et al., (2000) supported the wind driven coastal upwelling and increased river runoff during the southwest monsoon increased phytoplankton biomass dramatically which cause the enhance of phytoplankton productivity during post monsoon season.
The  BoB is featured with several cyclones in this season (Sarangi et al., 2008), which provide nutrient rich subsurface water to the surface, form eddies and intensify blooms (Chauhan et al., 2002; Madhu et al., 2002) and consequential roles in formation of POC.

### Northeast Monsoon (December- February) 
POC has found highest (181.80 ±22.34 mgm-³) during northeast monsoon characterized by very light northeasterly winds, mild temperature, dry weather, and lower SST (24.02 0C). Phytoplankton blooms patches generally occurred in this season (December to January) and disappear in the later months over the BoB. The blooms in this season are mainly attributed to the ocean upwelling driven Ekman pumping. Sarangi and Devi (2017) observed high nitrate dispersion on a synoptic scale during December and January. This nitrate is related to upwelling and convection processes which bring up the deeper and subsurface nutrient rich water to the surface during northeast monsoon. The winter convection process which brings nutrient rich water to the surface is responsible for the enhanced biological production (Tang et al., 2010). Highest POC of the BoB is mostly derived from phytoplankton (Fernandes et al., 2009). High POC (380 ± 28.7 mgm-³) was also accorded in northeast monsoon in the Yellow-Bohai sea of China (Fan et al., 2018).

### Pre-Monsoon (March – May)
Lowest POC (136.56±36.24mg m-³) was found during pre-monsoon (March-May) particularly in the month of May (115.38±41.31mg m-³) in BoB (Fig. 4.1). The gradual increase in SST results low POC on the BoB in this season and this relation was confirmed by previous studies (Nagamani et al., 2011).This increase of SST and decrease of wind speed. Insufficient freshwater influx can also be a reason for lower POC because fresh water influx causes high productivity by making  the waters of the upper layer less saline and highly stratified (Nagamani et al., 2011). Reduction of POC in pre-monsoon due to removal process or dilution was also observed by  Fan et al., (2018).

## Relationship between POC and SST

Recent evidence indicating that the variability of POC is negatively correlated with SST (Yu et al., 2019). An inverse relation was found between SST and POC for all the seasons in the BoB. The coefficient of regression was high (b= -15.86) in Southwest Monsoon (June- September) and low (b= -6.81) in northeast-monsoon (December-February) (6.81) (Fig.4.3). 
In northeast monsoon, we observed low negative coefficient. This scenario has been supported in the past by in situ observations in the Barents sea, Norway (Stramska and Bialogrodzka, 2016) and North Atlantic (Marra et al., 2015).

In contrast, in the southwest monsoon (June- September) water becomes warm in the study area. The warm sea surface temperature (SST’s) and the low salinity in the Bay of Bengal lead to strong stratification of the water column, which prevents the transport of nutrient rich bottom waters into the surface (Fernandes et al., 2009). Therefore, phytoplankton productivity declines which results a high negative correlation between SST and POC during this season.

## Relationship between POC and Chl-a

Phytoplankton production is the primary or main source for  POC in the open ocean surface waters (Siegel et al., 2013; Stramska, 2009; Stramski et al., 2008, 1999a; Yoder and Kennelly, 2006). Statistically a moderate positive significant relation was found between Chl-a and POC in all the seasons where the regression coefficient was ranged from 40.68 (pre-monsoon) to 78.01 (northeast monsoon). A significantly positive but relatively lower correlation coefficient (0.64–0.87) between POC and Chl-a (Fig. 4.4). Similar result was also found by Yu et al., (2019) in the North Pacific Ocean. Fernandes et al., (2009) also observed a fairly good significant positive relationship between POC and Chl-a was also reported by in the BoB.

Strong correlation between POC and Chl-a reveal that POC mostly derived from phytoplankton, not terrestrial organic matter to a great extent (Fernandes et al., 2009). The relation between POC and Chl-a was low (b = 40.68) in pre-monsoon, indicating that phytoplankton was relatively less dominant source of particulate carbon in these waters (Duan et al., 2014) and high (b=78.01) in northeast monsoon suggesting that POC is intensively  regulated by marine phytoplankton in association with  nutrient loading from riverine inputs (Liu et al., 2019a).

## Relationship between POC and wind vector

Water circulation on the inner shelf is primarily driven by wind (Nowlin et al., 2005). The monthly mean POC was weakly correlated with monthly wind speed (Fig. 4.5) among the seasons. Similar result was found by  Le et al. (2017) on the Louisiana Continental Shelf (USA). POC distribution is associated with wind direction. High POC distribution was found in northeast and post monsoon seasons when the prevailing wind was northeasterly direction. Low POC distribution was found southwest and pre-monsoon seasons when the prevailing wind was in southwesterly direction (Fig. 4.6).  Similar pattern was reported by Liu et al., (2015). 

Northeasterly winds prevail during winter, which drives westerly surface currents along the shore. In northeast monsoon, strong wind strengthens tidal currents, leading to intensive sediment resuspension. POC concentrations were positively correlated with wind speed (Liu et al., 2019a). Surface POC concentrations were high with high water velocity that were association with wind. Surface POC concentration decreased during the late period of tidal ebbing and early period of tidal flooding with low water velocity; the same pattern was observed during the late period of tidal flooding and early period of tidal ebbing (Liu et al., 2019a). 

## Validation of MODIS Aqua derived POC 

In-situ POC measurement ranged from 62.92 to 162.14 mgm-3 and are shown in Table 5. The correlation coefficient (Fig. 4.7) between in-situ and MODIS-Aqua satellite-derived POC was 0.74 with a root mean square error (RMSE) of 38.15% and mean relative error (MRE) of 32.17 % (Fig. 4.7). Lower values of RMSE indicate better fit of the of the model to the data representing how close the observed data points are to the model's predicted values (Yu et al., 2019).  Le et al. ( 2017) observed a similar performance as on the Louisiana Continental Shelf (LCS) in USA with R2=0.64, MRE=36.9%, and RMSE=49.8% using MODIS Aqua imagery. Duan et al. (2014) also observed a strong relationship between in-situ measured POC and MODIS estimated POC (N=16, RMSE=44.46%) using POC algorithm for the Yangtze River, China. General sources of error associated with any ocean-color product include differences introduced by choice of sensor, sensor calibration, and the atmospheric correction procedure used to retrieve remote-sensing reflectance (Rrs) (Evers-King et al., 2017). Further understanding of the sources of variability between POC and optical parameters can then be incorporated into future, semi-analytical algorithms. New understanding of these relationships may also inform future sensor development (e.g., hyperspectral sensors) and optical modeling technique (Evers-King et al., 2017).

## Relation with distance

A negative relation (-0.18) between the in-situ POC and distance with depth was found in the study area (Fig. 4.8). POC was decreasing from the lower depth area i.e., shelf zone (100-300m) to the higher depth area i.e., deep ocean. Similar result was observed in Fig.4.2 illustrated the raster image of multiyear monthly data. Because The primary productivity of phytoplankton is negatively correlated with the depth (Stramska, 2014). The observed decrease with depth of POC indicates heterotrophic uptake and/or dilution by inorganic material which results poor POC (Fernandes et al., 2009). So, phytoplankton distribution is mainly responsible for the phenomenon in the Bay of Bengal. The euphotic depth variability was also  accountable for the vertical distribution of POC (Liu et al., 2015).
