`r if (knitr::is_html_output()) '
# References {-}
'`
Allison, D.B., Stramski, D., Mitchell, B.G., 2010. Seasonal and interannual variability of particulate organic carbon within the Southern Ocean from satellite ocean color observations. J. Geophys. Res. 115, C06002. https://doi.org/10.1029/2009JC005347

Alongi, D.M., Boto, K.G., Tirendi, F., 1989. Effect of exported mangrove litter on bacterial productivity and dissolved organic carbon fluxes in adjacent tropical nearshore sediments. Mar. Ecol. Prog. Ser. Oldend. 56, 133–144.

Bai, Y., Cai, W.-J., He, X., Zhai, W., Pan, D., Dai, M., Yu, P., 2015. A mechanistic semi-analytical method for remotely sensing sea surface p CO 2 in river-dominated coastal oceans: A case study from the East China Sea. J. Geophys. Res. Ocean. 120, 2331–2349. https://doi.org/10.1002/2014JC010632

Bai, Y., He, X., Pan, D., Chen, C.T.A., Kang, Y., Chen, X., Cai, W.J., 2014. Summertime Changjiang River plume variation during 1998-2010. J. Geophys. Res. C Ocean. 119, 6238–6257. https://doi.org/10.1002/2014JC009866

Banglapedia, 2014. Bay Of Bengal EAFM 25–27.

Battin, T.J., Kaplan, L.A., Findlay, S., Hopkinson, C.S., Marti, E., Packman, A.I., Newbold, J.D., Sabater, F., 2008. Biophysical controls on organic carbon fluxes in fluvial networks. Nat. Geosci. 1, 95–100.

Bhosle, N.B., Dhople, V.M., Wagh, A.B., 1988. Distribution of particulate organic carbon in the central Arabian Sea. Proc. Indian Acad. Sci. - Earth Planet. Sci. 97, 35–47. https://doi.org/10.1007/BF02861625

Bianchi, T.S., 2007. Biogeochemistry of estuaries. Oxford University Press on Demand.
Bianchi, T.S., Bauer, J.E., 2012. Particulate Organic Carbon Cycling and Transformation, Treatise on Estuarine and Coastal Science. Elsevier Inc. https://doi.org/10.1016/B978-0-12-374711-2.00503-9

Bianchi, T.S., Wysocki, L.A., Stewart, M., Filley, T.R., McKee, B.A., 2007. Temporal variability in terrestrially-derived sources of particulate organic carbon in the lower Mississippi River and its upper tributaries. Geochim. Cosmochim. Acta 71, 4425–4437. https://doi.org/10.1016/j.gca.2007.07.011

Biddanda, B., Benner, R., 1997. Carbon, nitrogen, and carbohydrate fluxes during the production of particulate and dissolved organic matter by marine phytoplankton. Limnol. Oceanogr. 42, 506–518. https://doi.org/10.4319/lo.1997.42.3.0506

Boyer, J.N., Christian, R.R., Stanley, D.W., 1993. Patterns of phytoplankton primary productivity in the Neuse River estuary, North Carolina, USA. Mar. Ecol. Prog. Ser. Oldend. 97, 287–297.

Boynton, W.R., Kemp, W.M., Keefe, C.W., 1982. A comparative analysis of nutrients and other factors influencing estuarine phytoplankton production, in: Estuarine Comparisons. Elsevier, pp. 69–90.

Cahoon, L.B., 2002. The role of benthic microalgae in neritic ecosystems, in: Oceanography and Marine Biology, An Annual Review, Volume 37. CRC Press, pp. 55–94.

Chauhan, P., Mohan, M., Sarngi, R.K., Kumari, B., Nayak, S., Matondkar, S.G.P., 2002. Surface chlorophyll a estimation in the Arabian Sea using IRS-P4 Ocean Colour Monitor (OCM) satellite data. Int. J. Remote Sens. 23, 1663–1676. https://doi.org/10.1080/01431160110075866

Cheng, J., Shi, X.-Y., Zhang, C.-S., Wang, L.-S., Huang, S., Liu, D.-S., 2011. [Temporal and spatial distribution of particulate organic carbon in the Yellow Sea and East China Sea in spring]. Huan jing ke xue= Huanjing kexue 32, 2505–11.

Cloern, J.E., 1996. Phytoplankton bloom dynamics in coastal ecosystems: a review with some general lessons from sustained investigation of San Francisco Bay, California. Rev. Geophys. 34, 127–168.

Cong, P., Qu, L., Han, G., Yang, X., 2012. Remotely sensed detection and application analysis of ocean particulate organic carbon. Mar. Environ. Sci. 31, 300–304.

Dalsgaard, T., 2003. Benthic primary production and nutrient cycling in sediments with benthic microalgae and transient accumulation of macroalgae. Limnol. Oceanogr. 48, 2138–2150

De Jonge, V.N., Colijn, F., 1994. Dynamics of microphytobenthos biomass in the Ems estuary. Mar. Ecol. Prog. Ser. 185–196.

Den Hartog, C., 1970. The sea-grasses of the world. North-Holland, Amsterdam.

Duan, H., Feng, L., Ma, R., Zhang, Y., Arthur Loiselle, S., 2014. Variability of particulate organic carbon in inland waters observed from MODIS Aqua imagery. Environ. Res. Lett. 9. https://doi.org/10.1088/1748-9326/9/8/084011

Evers-King, H., Martinez-Vicente, V., Brewin, R.J.W., Dall’Olmo, G., Hickman, A.E., Jackson, T., Kostadinov, T.S., Krasemann, H., Loisel, H., Röttgers, R., Roy, S., Stramski, D., Thomalla, S., Platt, T., Sathyendranath, S., 2017. Validation and intercomparison of ocean color algorithms for estimating particulate organic carbon in the oceans. Front. Mar. Sci. 4, 1–20. https://doi.org/10.3389/fmars.2017.00251

Fan, H., Wang, X., Zhang, H., Yu, Z., 2018. Spatial and temporal variations of particulate organic carbon in the Yellow-Bohai Sea over 2002-2016. Sci. Rep. https://doi.org/10.1038/s41598-018-26373-w

Fernandes, L., Bhosle, N.B., Matondkar, S.G.P., Bhushan, R., 2009. Seasonal and spatial distribution of particulate organic matter in the Bay of Bengal. J. Mar. Syst. 77, 137–147.

Fingas, M., 2018. Remote Sensing for Marine Management, in: World Seas: An Environmental Evaluation. Elsevier, pp. 103–119. https://doi.org/10.1016/b978-0-12-805052-1.00005-x

Fonseca, M.S., Kenworthy, W.J., 1987. Effects of current on photosynthesis and distribution of seagrasses. Aquat. Bot. 27, 59–78.

Gaiser, P.W., Member, S., Germain, K.M.S., Member, S., Twarog, E.M., Poe, G.A., Purdy, W., Richardson, D., Grossman, W., Jones, W.L., Spencer, D., Golba, G., Cleveland, J., Choy, L., Bevilacqua, R.M., Chang, P.S., Member, S., 2004. The WindSat Spaceborne Polarimetric Microwave Radiometer : Sensor Description and Early Orbit Performance. IEEE Trans. Geosci. Remote Sens. 42.

Gardner, W.D., Mishonov, A. V., Richardson, M.J., 2006. Global POC concentrations from in-situ and satellite data. Deep. Res. Part II Top. Stud. Oceanogr. 53, 718–740. https://doi.org/10.1016/j.dsr2.2006.01.029

Gomes, H.R., Goes, J.I., Saino, T., 2000. Influence of physical processes and freshwater discharge on the seasonality of phytoplankton regime in the Bay of Bengal. Cont. Shelf Res. 20, 313–330. https://doi.org/10.1016/S0278-4343(99)00072-2

Gould, D.M., Gallagher, E.D., 1990. Field measurement of specific growth rate, biomass, and primary production of benthic diatoms of Savin Hill Cove, Boston. Limnol. Oceanogr. 35, 1757–1770.

Green, E.P., Short, F.T., Frederick, T., 2003. World atlas of seagrasses. Univ of California Press.

Haibo, Z., Luning, Y., Lisha, W., Shaofeng, P., Xiaoyong, S., 2016. Distribution and source analyses of particulate organic carbon in the Yellow Sea and Bohai Sea during summer, 2013. Haiyang Xuebao 38, 24–35.

He, X., Bai, Y., Pan, D., Huang, N., Dong, X., Chen, J., Chen, C.T.A., Cui, Q., 2013. Using geostationary satellite ocean color data to map the diurnal dynamics of suspended particulate matter in coastal waters. Remote Sens. Environ. 133, 225–239. https://doi.org/10.1016/j.rse.2013.01.023

Hemminga, M.A., Duarte, C.M., 2000. Seagrass ecology. Cambridge University Press.
Hussain, M.G., Failler, P., Al Karim, A., Alam, M.K., 2017. Review on opportunities, constraints and challenges of blue economy development in Bangladesh. J. Fish. Life Sci. 2, 45–57.

Jeremy Werdell, P., McClain, C.R., 2019. Satellite remote sensing: Ocean color, 3rd ed, Encyclopedia of Ocean Sciences. Elsevier Inc. https://doi.org/10.1016/B978-0-12-409548-9.10817-6

Kavak, M.T., Karadogan, S., 2011. The relationship between sea surface temperature and chlorophyll concentration of phytoplanktons in the Black Sea using remote sensing techniques Author Details. J. Environ. Biol 32, 493–498.

Khatun, M.A., Rashid, M.B., Hygen, H.O., 2016. Climate of Bangladesh. MET Rep. 2387–4201.

Knap, A.H., Michaels, A., Close, A.R., Ducklow, H., Dickson, A.G., 1996. Protocols for the joint global ocean flux study (JGOFS) core measurements.

Le, C., Lehrter, J.C., Hu, C., MacIntyre, H., Beck, M.W., 2017. Satellite observation of particulate organic carbon dynamics in two river-dominated estuaries. J. Geophys. Res. Ocean. 122, 555–569. https://doi.org/10.1002/2016JC012275

Le, C., Zhou, X., Hu, C., Lee, Z., Li, L., Stramski, D., 2018. A Color-Index-Based Empirical Algorithm for Determining Particulate Organic Carbon Concentration in the Ocean From Satellite Observations. J. Geophys. Res. Ocean. 123, 7407–7419. https://doi.org/10.1029/2018JC014014

Lee, D., Jeong, J.-Y., Jang, H.K., Min, J.-O., Kim, M.J., Youn, S.H., Lee, T., Lee, S.H., 2019. Comparison of Particulate Organic Carbon to Chlorophyll-a Ratio Based on the Ocean Color Satellite Data at the Ieodo and Socheongcho Ocean Research Stations. J. Coast. Res. 90, 267. https://doi.org/10.2112/si90-033.1

Liu, D., Bai, Y., He, X., Pan, D., Chen, C.T.A., Li, T., Xu, Y., Gong, C., Zhang, L., 2019a. Satellite-derived particulate organic carbon flux in the Changjiang River through different stages of the Three Gorges Dam. Remote Sens. Environ. 223, 154–165. https://doi.org/10.1016/j.rse.2019.01.012

Liu, D., Bai, Y., He, X., Tao, B., Pan, D., Chen, C.T.A., Zhang, L., Xu, Y., Gong, C., 2019b. Satellite estimation of particulate organic carbon flux from Changjiang River to the estuary. Remote Sens. Environ. 223, 307–319. https://doi.org/10.1016/j.rse.2019.01.025

Liu, D., Pan, D., Bai, Y., He, X., Wang, D., Wei, J.A., Zhang, L., 2015. Remote sensing observation of particulate organic carbon in the Pearl River Estuary. Remote Sens. 7, 8683–8704. https://doi.org/10.3390/rs70708683

Lucas, L. V, Cloern, J.E., 2002. Effects of tidal shallowing and deepening on phytoplankton production dynamics: A modeling study. Estuaries 25, 497–507.

Madhu, N. V, Maheswaran, P.A., Jyothibabu, R., Sunil, V., Revichandran, C., Balasubramanian, T., Gopalakrishnan, T.C., Nair, K.K.C., 2002. Enhanced biological production off Chennai triggered by October 1999 super cyclone (Orissa), CURRENT SCIENCE. Indian Academy of Sciences.

Malone, T.C., Crocker, L.H., Pike, S.E., Wendler, B.W., 1988. Influences of river flow on the dynamics of phytoplankton production in a partially stratified estuary. Mar. Ecol. Prog. Ser. Oldend. 48, 235–249.

Marra, J.F., Dickey, T.D., Plueddemann, A.J., Weller, R.A., Kinkade, C.S., Stramska, M., Phytoplankton, M., 2015. Phytoplankton bloom phenomena in the North Atlantic Ocean and Arabian Sea. North Atl. Ocean Arab. Sea.-ICES J. Mar. Sci. 72, 2021–2028. https://doi.org/10.1093/icesjms/fsu241

Menzel, D.W., 1974. Primary productivity, dissolved and particulate organic matter, and the sites of oxidation of organic matter. Sea. Mar. Chem. 5, 654–678.
Murray, J.W., 2000. The oceans, International Geophysics. https://doi.org/10.1016/S0074-6142(00)80116-3

Nagamani, P. V., Shikhakolli, R., Chauhan, P., 2011. Phytoplankton Variability in the Bay of Bengal During Winter Monsoon Using Oceansat-1 Ocean Colour Monitor Data. J. Indian Soc. Remote Sens. 39, 117–126. https://doi.org/10.1007/s12524-010-0056-0
Nandakumar, K., Venkat, K., Bhosle, N.B., 1987. Distribution of particulate organic carbon in the central Bay of Bengal. Proc. Indian Acad. Sci. - Earth Planet. Sci. 96, 189–193. https://doi.org/10.1007/BF02839268

NASA, 2014a. Chlorophyll a (chlor_a) [WWW Document]. NASA. URL https://oceancolor.gsfc.nasa.gov/atbd/chlor_a/ (accessed 2.21.20).

NASA, 2014b. Long-Wave Sea Surface Temperature (SST) [WWW Document]. NASA. URL https://oceancolor.gsfc.nasa.gov/atbd/sst/ (accessed 2.21.20).

Nowlin, W.D., Jochens, A.E., DiMarco, S.F., Reid, R.O., Howard, M.K., 2005. Low-frequency circulation over the Texas-Louisiana continental shelf. Geophys. Monogr. Geophys. UNION 161, 219.

O’Donohue, M.J.H., Dennison, W.C., 1997. Phytoplankton productivity response to nutrient concentrations, light availability and temperature along an Australian estuarine gradient. Estuaries 20, 521–533.

Parsons, T.R., Maita, Y., Lalli, C.M., 1984. A manual of chemical and biological methods for seawater analysis. Pergamon Press.

Pavia, F.J., Anderson, R.F., Lam, P.J., Cael, B.B., Vivancos, S.M., Fleisher, M.Q., Lu, Y., Zhang, P., Cheng, H., Lawrence Edwards, R., 2019. Shallow particulate organic carbon regeneration in the South Pacific Ocean. Proc. Natl. Acad. Sci. U. S. A. 116, 9753–9758. https://doi.org/10.1073/pnas.1901863116

Pinckney, J.L., Zingmark, R.G., 1993. MODELING THE ANNUAL PRODUCTION OF INTERTIDAL BENTHIC MICROALGAE IN ESTUARINE ECOSYSTEMS 1. J. Phycol. 29, 396–407.

Rizzo, W.M., Lackey, G.J., Christian, R.R., 1992. Significance of euphotic, subtidal sediments to oxygen and nutrient cycling in a temperate estuary. Mar. Ecol. Prog. Ser. Oldend. 86, 51–61.

Roca, M., Chen, K., Pérez-Gálvez, A., 2016. Chlorophylls, in: Handbook on Natural Pigments in Food and Beverages: Industrial Applications for Improving Food Color. Elsevier Inc., pp. 125–158. https://doi.org/10.1016/B978-0-08-100371-8.00006-3

Sarangi, R.K., Devi, K.N., 2017. Space-based observation of chlorophyll, sea surface temperature, nitrate, and sea surface height anomaly over the Bay of Bengal and Arabian Sea. Adv. Sp. Res. 59, 33–44. https://doi.org/10.1016/j.asr.2016.08.038

Sarangi, R.K., Nayak, S., Panigrahy, & R.C., 2008. Monthly variability of chlorophyll and associated physical parameters in the southwest Bay of Bengal water using remote sensing data, Indian Journal of Marine Sciences.

Sharp, J.H., 1974. Improved analysis for “particulate” organic carbon and nitrogen from seawater1. Limnol. Oceanogr. 19, 984–989. https://doi.org/10.4319/lo.1974.19.6.0984

Shen, Zhiliang; Yang, Heming & Liu, Q., 2020. Particulate Organic Carbon and Its Composition in Jiaozhou Bay. Springer Berlin Heidelberg. https://doi.org/10.1007/978-3-662-58169-8_18

Shen, F., Zhou, Y., Li, J., He, Q., Verhoef, W., 2013. Remotely sensed variability of the suspended sediment concentration and its response to decreased river discharge in the Yangtze estuary and adjacent coast. Cont. Shelf Res. https://doi.org/10.1016/j.csr.2013.09.002

Shi, X., Zhang, T., Zhang, C., Cheng, J., 2011. Spatial and temporal distribution of particulate organic carbon in Yellow Sea and East China Sea. Mar. Environ. Sci. 1.

Siegel, D.A., Behrenfeld, M.J., Maritorena, S., McClain, C.R., Antoine, D., Bailey, S.W., Bontempi, P.S., Boss, E.S., Dierssen, H.M., Doney, S.C., Eplee, R.E., Evans, R.H., Feldman, G.C., Fields, E., Franz, B.A., Kuring, N.A., Mengelt, C., Nelson, N.B., Patt, F.S., Robinson, W.D., Sarmiento, J.L., Swan, C.M., Werdell, P.J., Westberry, T.K., Wilding, J.G., Yoder, J.A., 2013. Regional to global assessments of phytoplankton dynamics from the SeaWiFS mission. Remote Sens. Environ. 135, 77–91. https://doi.org/10.1016/j.rse.2013.03.025

Stramska, M., 2014. Particulate organic carbon in the surface waters of the North Atlantic: Spatial and temporal variability based on satellite ocean colour. Int. J. Remote Sens. 35, 4717–4738. https://doi.org/10.1080/01431161.2014.919686

Stramska, M., 2009. Particulate organic carbon in the global ocean derived from SeaWiFS ocean color. Deep. Res. Part I Oceanogr. Res. Pap. 56, 1459–1470. https://doi.org/10.1016/j.dsr.2009.04.009

Stramska, M., Bialogrodzka, J., 2016. Satellite observations of seasonal and regional variability of particulate organic carbon concentration in the Barents Sea. Oceanologia 58, 249–263. https://doi.org/10.1016/j.oceano.2016.04.004

Stramski, D., Reynolds, R.A., Babin, M., Kaczmarek, S., Lewis, M.R., Röttgers, R., Sciandra, A., Stramska, M., Twardowski, M.S., Franz, B.A., Claustre, H., 2008.
Relationships between the surface concentration of particulate organic carbon and optical properties in the eastern South Pacific and eastern Atlantic Oceans, Biogeosciences.

Stramski, D., Reynolds, R.A., Kahru, M., Mitchell, B.G., 1999a. Estimation of particulate organic carbon in the ocean from satellite remote sensing. Science (80-. ). 285, 239–242. https://doi.org/10.1126/science.285.5425.239

Stramski, D., Reynolds, R.A., Kahru, M., Mitchell, B.G., 1999b. Estimation of particulate organic carbon in the ocean from satellite remote sensing. Science (80-. ). 285, 239–242.

Sullivan, M.J., Moncreiff, C.A., 1990. Edaphic algae are an important component of salt marsh food-webs: evidence from multiple stable isotope analyses. Mar. Ecol. Prog. Ser. Oldend. 62, 149–159.

Świrgoń, M., Stramska, M., 2015. Comparison of in situ and satellite ocean color determinations of particulate organic carbon concentration in the global ocean. Oceanologia 57, 25–31. https://doi.org/10.1016/j.oceano.2014.09.002

Tang, D., Satyanarayana, B., Singh, R.P., Zhao, H., 2010. Satellite Remote Sensing of chlorophyll-a distribution in the Northeast Arabian Sea.

Thompson, P.A., 1998. Spatial and temporal patterns of factors influencing phytoplankton in a salt wedge estuary, the Swan River, Western Australia. Estuaries 21, 801–817.

Walton, C.C., Pichel, W.G., Sapper, J.F., May, D.A., 1998. The development and operational application of nonlinear algorithms for the measurement of sea surface temperatures with the NOAA polar-orbiting environmental satellites. J. Geophys. Res. Ocean. 103, 27999–28012. https://doi.org/10.1029/98JC02370

Wang, X., Ma, H., Li, R., Song, Z., Wu, J., 2012. Seasonal fluxes and source variation of organic carbon transported by two major Chinese Rivers: The Yellow River and Changjiang (Yangtze) River. Global Biogeochem. Cycles 26.
https://doi.org/10.1029/2011GB004130

Wangersky, P.J., 1977. The role of particulate matter in the productivity of surface waters. Helgoländer Wissenschaftliche Meeresuntersuchungen 30, 546–564. https://doi.org/10.1007/BF02207860

Ward, L.G., Kemp, W.M., Boynton, W.R., 1984. The influence of waves and seagrass communities on suspended particulates in an estuarine embayment. Mar. Geol. 59, 85–103.

Webster, I.T., Ford, P.W., Hodgson, B., 2002. Microphytobenthos contribution to nutrient-phytoplankton dynamics in a shallow coastal lagoon. Estuaries 25, 540–551.

Wentz, F.J., L.Ricciardulli, C.Gentemann, T. Meissner, K.A. Hilburn, J.S., 2013. Remote Sensing Systems Coriolis WindSat [indicate whether you used Daily, 3-Day, Weekly, or Monthly] Environmental Suite on 0.25 deg grid, Version 7.0.1, [indicate subset if used]. Remote Sensing Systems, Santa Rosa, CA [WWW Document]. URL http://www.remss.com/missions/windsat/ (accessed 3.22.20).

Wetzel, R.G., 1995. Death, detritus, and energy flow in aquatic ecosystems. Freshw. Biol. 33, 83–89. https://doi.org/10.1111/j.1365-2427.1995.tb00388.x
Williams, P.J.L.E., 1975. Biological and chemical aspects of dissolved oraganic materials in seawater. Chem. Oceanogr. 301–363.

Williams, P.M., 1971. The distribution and cycling of organic matter in the ocean. In, Organic Compounds in Aquatic Environment. SJ FAUST and JV HUNTER (eds.) 145-163.

Xie, F., Tao, Z., Zhou, X., Lv, T., Wang, J., 2019. Spatial and Temporal Variations of Particulate Organic Carbon Sinking Flux in Global Ocean from 2003 to 2018. Remote Sens. 11, 2941. https://doi.org/10.3390/rs11242941

Xu, K., Milliman, J.D., 2009. Seasonal variations of sediment discharge from the Yangtze River before and after impoundment of the Three Gorges Dam. Geomorphology 104, 276–283. https://doi.org/10.1016/j.geomorph.2008.09.004

Yoder, J., Kennelly, M., 2006. What Have We Learned About Ocean Variability from Satellite Ocean Color Imagers? Oceanography 19, 152–171. https://doi.org/10.5670/oceanog.2006.98

Yu, J., Wang, X., Fan, H., Zhang, R.H., 2019. Impacts of Physical and Biological Processes on Spatial and Temporal Variability of Particulate Organic Carbon in the North Pacific Ocean during 2003–2017. Sci. Rep. 9, 1–15. https://doi.org/10.1038/s41598-019-53025-4

Zhu, G.H., Liu, Y.L., Chen, L.H., Yu, P.S., Jin, M., Liu, Z.L., 2011. Studies on Phytoplankton and Particulate Organic Carbon in the Southern Ocean. Appl. Mech. Mater. 137, 344–352. https://doi.org/10.4028/www.scientific.net/amm.137.344

Zibordi, G., Mélin, F., 2017. An evaluation of marine regions relevant for ocean color system vicarious calibration. Remote Sens. Environ. 190, 122–136. https://doi.org/10.1016/j.rse.2016.11.020

